Update

diff --git a/home/.git-hooks/pre-commit b/home/.git-hooks/pre-commit
--- a/home/.git-hooks/pre-commit
+++ b/home/.git-hooks/pre-commit
@@ -1,6 +1,30 @@
 #!/usr/bin/env bash
-
-# set -o xtrace
+#
+# Author: James Cherti
+# URL: https://github.com/jamescherti/jc-dev
+#
+# Distributed under terms of the MIT license.
+#
+# Copyright (C) 2004-2026 James Cherti
+#
+# Permission is hereby granted, free of charge, to any person obtaining a copy
+# of this software and associated documentation files (the “Software”), to deal
+# in the Software without restriction, including without limitation the rights
+# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
+# copies of the Software, and to permit persons to whom the Software is
+# furnished to do so, subject to the following conditions:
+#
+# The above copyright notice and this permission notice shall be included in all
+# copies or substantial portions of the Software.
+#
+# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
+# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+# SOFTWARE.
+#
 
 set -euf -o pipefail
 IFS=$'\n\t'
@@ -8,8 +32,6 @@ echo "[HOOK] pre-commit"
 
 AUTHORINFO=$(git var GIT_AUTHOR_IDENT)
 echo "[INFO] Author: $AUTHORINFO"
-# EMAIL=$(printf '%s\n' "${AUTHORINFO}" | sed -n 's/^.* <\(.*\)> .*$/\1/p')
-# NAME=$(printf '%s\n' "${AUTHORINFO}" | sed -n 's/^\(.*\) <.*$/\1/p')
 
 #-------------------------------------------------------------------------------
 # Error handler
@@ -21,8 +43,6 @@ error_handler() {
     "(${BASH_COMMAND} exited with status $errno)" >&2
   exit "${errno}"
 }
-trap "error_handler" ERR
-set -o errtrace
 
 check_email_change() {
   if type -P git-setup &>/dev/null && ! git-setup; then
@@ -127,7 +147,7 @@ update_list_files() {
 check_non_ascii() {
   # If you want to allow non-ASCII filenames set this variable to true.
   # allownonascii=$(git config --bool hooks.allownonascii)
-  # local allownonascii
+  local allownonascii
   allownonascii=false
 
   # Cross platform projects tend to avoid non-ASCII filenames; prevent
@@ -137,11 +157,11 @@ check_non_ascii() {
     # Note that the use of brackets around a tr range is ok here, (it's even
     # required, for portability to Solaris 10's /usr/bin/tr), since the square
     # bracket bytes happen to fall in the designated range.
-    local fresult=''
+    local result=''
     # TODO: REUSE the list of files
-    fresult=$(git diff --cached --name-only --diff-filter=A -z "$AGAINST" | LC_ALL=C tr -d '[ -~]\0' | wc -c)
-    if [ "$fresult" -ne "0" ]; then
-      error_begin
+    result=$(git diff --cached --name-only --diff-filter=A -z "$AGAINST" | LC_ALL=C tr -d '[ -~]\0' | wc -c)
+    if [ "$result" -ne "0" ]; then
+      error "--------------------------------------------------------------------"
       echo "[ERROR] Attempt to add a non-ASCII file name (a file name with accents?):"
       git diff --cached --name-only --diff-filter=A -z "$AGAINST" | LC_ALL=C cat
 
@@ -152,14 +172,32 @@ check_non_ascii() {
       echo "        rename the non-ASCII file name to an valid ASCII name with:"
       echo "        git mv nonasciifile validfilename"
       echo
-      error_end
+      error "--------------------------------------------------------------------"
       exit 1
     fi
   fi
 }
 
+check_typographic_apostrophes() {
+  local file
+  local fault=0
+  for file in "${MODIFIED_FILES[@]}"; do
+    # Extract only the added lines in the staged changes and grep for
+    # typographic quotes
+    if git diff --cached -- "$file" | grep '^+' | grep -v '^+++' | grep -q -E "’|‘"; then
+      error "[ERROR] Typographic apostrophe ('’' or '‘') introduced in staged changes of: $file"
+      # Print the offending lines to stderr for visibility
+      git diff --cached -- "$file" | grep '^+' | grep -v '^+++' | grep -E "’|‘" >&2
+      fault=1
+    fi
+  done
+  if [ "$fault" -eq 1 ]; then
+    exit 1
+  fi
+}
+
 check_syntax() {
-  SYNTAX CHECK
+  # SYNTAX CHECK
   echo
   echo "[CHECK] Checking the Syntax"
   local file
@@ -177,14 +215,9 @@ check_pre_commit() {
   else
     #!/usr/bin/env bash
     # File generated by pre-commit: https://pre-commit.com
-    # ID: 138fd403232d2ddd5efb44317e38bf03
-
-    # start templated
     if type -P pre-commit &>/dev/null; then
       INSTALL_PYTHON=/usr/bin/python3
       ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
-      # end templated
-
       HERE="$(cd "$(dirname "$0")" && pwd)"
       ARGS+=(--hook-dir "$HERE" -- "$@")
 
@@ -206,7 +239,7 @@ check_arch_linux() {
     if ! [[ -f .SRCINFO ]] || [[ PKGBUILD -nt .SRCINFO ]]; then
       echo "[INFO] Update .SRCINFO"
       makepkg --printsrcinfo >.SRCINFO
-      if git status --porcelain "$file" | grep -q '^[ M]'; then
+      if git status --porcelain .SRCINFO | grep -q '^[ M]'; then
         makepkg --verifysource -f
         echo "[FAILED] The .SRCINFO file has been updated successfully." \
           "Please commit again."
@@ -219,9 +252,15 @@ check_arch_linux() {
 }
 
 main() {
+  trap "error_handler" ERR
+  set -o errtrace
+
   echo "[INFO] client side pre-commit hook started"
   init
-  [ "$INIT_SUCCESS" -ne "1" ] && die "You need to run init() before main()"
+  [ "$INIT_SUCCESS" -ne "1" ] && {
+    error "You need to run init() before main()"
+    exit 1
+  }
 
   # Update the list of files
   update_list_files
@@ -230,6 +269,7 @@ main() {
   check_email_change "$@"
   check_gpg
   check_non_ascii
+  check_typographic_apostrophes
   # check_syntax
 
   check_arch_linux
