Update enter-chroot

diff --git a/home/.bin/enter-chroot b/home/.bin/enter-chroot
--- a/home/.bin/enter-chroot
+++ b/home/.bin/enter-chroot
@@ -28,7 +28,11 @@
 # this program. If not, see <https://www.gnu.org/licenses/>.
 #
 
-set -euf -o pipefail
+set -euo pipefail
+set -o errtrace
+
+declare -a CHROOT_MOUNTS
+declare CHROOT_DIR=""
 
 usage() {
   printf 'Usage: %s <chroot_directory>\n' "${0##*/}" >&2
@@ -37,12 +41,11 @@ usage() {
 
 cleanup() {
   local target
+  local i
 
-  for target in \
-    "$CHROOT_DIR/run" \
-    "$CHROOT_DIR/sys" \
-    "$CHROOT_DIR/proc" \
-    "$CHROOT_DIR/dev"; do
+  # Unmount in reverse order of mounting
+  for ((i = ${#CHROOT_MOUNTS[@]} - 1; i >= 0; i--)); do
+    target="${CHROOT_MOUNTS[i]}"
     if mountpoint -q "$target"; then
       umount -R "$target" \
         || printf 'Warning: failed to unmount %s\n' "$target" >&2
@@ -70,24 +73,37 @@ validate_chroot() {
 }
 
 mount_fs() {
-  mkdir -p \
-    "$CHROOT_DIR/dev" \
-    "$CHROOT_DIR/proc" \
-    "$CHROOT_DIR/sys" \
-    "$CHROOT_DIR/run"
+  mkdir -p "${CHROOT_MOUNTS[@]}"
 
-  mount --rbind /dev "$CHROOT_DIR/dev"
-  mount --make-rslave "$CHROOT_DIR/dev"
+  if ! mountpoint -q "$CHROOT_DIR/dev"; then
+    mount --rbind /dev "$CHROOT_DIR/dev"
+    mount --make-rslave "$CHROOT_DIR/dev"
+  fi
 
-  mount -t proc proc "$CHROOT_DIR/proc"
+  if ! mountpoint -q "$CHROOT_DIR/proc"; then
+    mount -t proc proc "$CHROOT_DIR/proc"
+  fi
 
-  mount --rbind /sys "$CHROOT_DIR/sys"
-  mount --make-rslave "$CHROOT_DIR/sys"
+  if ! mountpoint -q "$CHROOT_DIR/sys"; then
+    mount --rbind /sys "$CHROOT_DIR/sys"
+    mount --make-rslave "$CHROOT_DIR/sys"
+  fi
 
-  mount --bind /run "$CHROOT_DIR/run"
+  if ! mountpoint -q "$CHROOT_DIR/run"; then
+    mount --bind /run "$CHROOT_DIR/run"
+  fi
+}
+
+# shellcheck disable=SC2317
+error_handler() {
+  local errno="$?"
+  echo -- "Error: ${BASH_SOURCE[1]}:${BASH_LINENO[0]}" \
+    "(${BASH_COMMAND} exited with status $errno)" >&2
+  exit "${errno}"
 }
 
 main() {
+  trap "error_handler" ERR
   require_root
 
   if [[ "$#" -ne 1 ]]; then
@@ -95,6 +111,13 @@ main() {
   fi
 
   CHROOT_DIR="$(realpath "$1")"
+
+  CHROOT_MOUNTS=(
+    "$CHROOT_DIR/dev"
+    "$CHROOT_DIR/proc"
+    "$CHROOT_DIR/sys"
+    "$CHROOT_DIR/run"
+  )
 
   validate_chroot
 
