Update

diff --git a/home/.bin/run-emacs b/home/.bin/run-emacs
--- a/home/.bin/run-emacs
+++ b/home/.bin/run-emacs
@@ -47,7 +47,7 @@ set -euf -o pipefail
 
 # Safely assign default values
 RUN_EMACS_FORCE="${RUN_EMACS_FORCE:-0}"
-RUN_EMACS_BIN="${RUN_EMACS_BIN:-emacs}"
+RUN_EMACS_BIN="${RUN_EMACS_BIN:-}"
 
 # Emacs: lsp-mode can be compiled in 2 modes plist and hash-table based
 # lsp-use-plists flag. plists provide better performance in deserialization and
@@ -78,6 +78,11 @@ is-emacs-server-running() {
 }
 
 main() {
+  if [[ $RUN_EMACS_BIN == "" ]]; then
+    echo "Error: \$RUN_EMACS_BIN is not set or empty." >&2
+    exit 1
+  fi
+
   # Correctly check if the binary exists in the system PATH
   if ! RUN_EMACS_BIN=$(type -P "$RUN_EMACS_BIN" 2>/dev/null); then
     echo "Error: Command not found in PATH: '$RUN_EMACS_BIN'" >&2
diff --git a/home/.bin/run-emacs-use-package b/home/.bin/run-emacs-use-package
--- a/home/.bin/run-emacs-use-package
+++ b/home/.bin/run-emacs-use-package
@@ -30,10 +30,12 @@ OSFAMILY=$(~/.local/bin/osid)
 # Never change this to master
 export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-emacs-30/bin/emacs"
 if ! [[ -f "$RUN_EMACS_BIN" ]]; then
-  export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/tag-emacs-30.2/bin/emacs"
-  if ! [[ -f "$RUN_EMACS_BIN" ]]; then
-    RUN_EMACS_BIN=emacs
-  fi
+  #   export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/tag-emacs-30.2/bin/emacs"
+  #   if ! [[ -f "$RUN_EMACS_BIN" ]]; then
+  #     RUN_EMACS_BIN=emacs
+  #   fi
+  echo "Error: Not found: $RUN_EMACS_BIN" >&2
+  exit 1
 fi
 
 EMACS_D="$HOME/.emacs-use-package.d/"
