Update

diff --git a/home/.bin/run-emacs b/home/.bin/run-emacs
--- a/home/.bin/run-emacs
+++ b/home/.bin/run-emacs
@@ -70,16 +70,15 @@ is-emacs-server-running() {
   emacsclient -e "(+ 1 1)" &>/dev/null
 }
 
+EMACS_D=""
 load_emacs_profile() {
   RUN_EMACS_BIN="${RUN_EMACS_BIN:-}"
-  OSFAMILY=$(~/.local/bin/osid)
+  OSFAMILY=$(~/.local/bin/osid 2>/dev/null || echo "unknown")
   EMACS_PROFILE="${EMACS_PROFILE:-}"
-  EMACS_D=""
 
   if [[ $OSFAMILY = arch ]]; then
     if ! [[ -f "$RUN_EMACS_BIN" ]]; then
-      export \
-        RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-master/bin/emacs"
+      export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-master/bin/emacs"
       EMACS_D="$HOME/.emacs-master.d/"
     fi
   fi
@@ -90,12 +89,12 @@ load_emacs_profile() {
   fi
 
   if ! [[ -f "$RUN_EMACS_BIN" ]]; then
-    export \
-      RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-master/bin/emacs"
+    export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-master/bin/emacs"
     EMACS_D="$HOME/.emacs-master.d/"
     # export RUN_EMACS_BIN="/opt/local/$USER/$OSFAMILY/emacs/branch-emacs-31/bin/emacs"
   fi
 
+  echo "[INFO] Emacs binary: $RUN_EMACS_BIN"
   if ! [[ -f "$RUN_EMACS_BIN" ]]; then
     echo "Error: The Emacs binary does not exist: $RUN_EMACS_BIN" >&2
     exit 1
@@ -115,8 +114,8 @@ load_emacs_profile() {
   #   fi
   # fi
 
-  if [[ -f "$EMACS_D" ]]; then
-    echo "Error: The Emacs user directory does not exist: $EMACS_D" >&2
+  if ! [[ -d "$EMACS_D" ]]; then
+    echo "Error: The Emacs user directory does not exist: '$EMACS_D'" >&2
     exit 1
   fi
   export EMACSNATIVELOADPATH="$EMACS_D/var/eln-cache/:"
@@ -124,9 +123,14 @@ load_emacs_profile() {
 }
 
 main() {
+  set -x
   load_emacs_profile
 
   EMACS_ARGS_DICT+=("--init-directory")
+  if [[ $EMACS_D = "" ]]; then
+    echo "Error: \$EMACS_D is empty." >&2
+    exit 1
+  fi
   EMACS_ARGS_DICT+=("$EMACS_D")
 
   if [[ $RUN_EMACS_BIN == "" ]]; then
