Update

diff --git a/home/.bin/xdevenv-emacs b/home/.bin/xdevenv-emacs
--- a/home/.bin/xdevenv-emacs
+++ b/home/.bin/xdevenv-emacs
@@ -19,12 +19,14 @@
 # this program. If not, see <https://www.gnu.org/licenses/>.
 #
 
+if [[ $EMACS_BIN = "" ]]; then
+  EMACS_BIN="$HOME/.bin/run-emacs"
+fi
+
 # This have to be defined after sourcing profile and bashrc
 # set -euf -o pipefail
 set -e
 set -u
-
-EMACS_BIN="$HOME/.bin/run-emacs"
 
 # # EMACS_BIN="$HOME/.bin/run-emacs-30"
 # EMACS_BIN="$HOME/.bin/run-emacs-master"
@@ -32,66 +34,66 @@ EMACS_BIN="$HOME/.bin/run-emacs"
 # EMACS_BIN="$HOME/.bin/run-emacs-elpaca"
 
 is_wayland() {
-    [[ $XDG_SESSION_TYPE = wayland ]] || return 1
+  [[ $XDG_SESSION_TYPE = wayland ]] || return 1
 }
 
 is_gnome() {
-    [[ $XDG_CURRENT_DESKTOP = GNOME ]] || return 1
+  [[ $XDG_CURRENT_DESKTOP = GNOME ]] || return 1
 }
 
 has_run_or_raise() {
-    test -d ~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz
+  test -d ~/.local/share/gnome-shell/extensions/run-or-raise@edvard.cz
 }
 
 bg_run() {
-    # nohup
-    # --chdir "$HOME" <- breaks ./apps in a different directory
-    "$@" &
-    disown
+  # nohup
+  # --chdir "$HOME" <- breaks ./apps in a different directory
+  "$@" &
+  disown
 }
 
 show_window() {
-    local proc_name="$1"
-    local win_name="$2"
+  local proc_name="$1"
+  local win_name="$2"
 
-    if is_wayland; then
-        if pgrep "$proc_name" &>/dev/null; then
-            echo "[IGNORE] The process $proc_name is already running"
-            return 0
-        fi
-    else
-        if wmctrl -x -a "$win_name"; then
-            echo "[FOCUS WINDOW] $win_name"
-            return 0
-        elif [[ $# -gt 0 ]]; then
-            shift
-            shift
-            echo "[RUN]" "$@"
-            bg_run "$@"
-        fi
+  if is_wayland; then
+    if pgrep "$proc_name" &>/dev/null; then
+      echo "[IGNORE] The process $proc_name is already running"
+      return 0
     fi
+  else
+    if wmctrl -x -a "$win_name"; then
+      echo "[FOCUS WINDOW] $win_name"
+      return 0
+    elif [[ $# -gt 0 ]]; then
+      shift
+      shift
+      echo "[RUN]" "$@"
+      bg_run "$@"
+    fi
+  fi
 
-    return 1
+  return 1
 }
 
 start-or-raise-emacs() {
-    if pgrep --exact emacs &>/dev/null; then
-        if is_wayland; then
-            if is_gnome && has_run_or_raise; then
-                gdbus call --session --dest org.gnome.Shell \
-                    --object-path /org/gnome/Shell/Extensions/RunOrRaise \
-                    --method org.gnome.Shell.Extensions.RunOrRaise.Call \
-                    ",${EMACS_BIN},,/Lightemacs$/"
-            else
-                bg_run "$EMACS_BIN"
-            fi
-        else
-            show_window emacs "emacs.Emacs" "$EMACS_BIN"
-        fi
-    else
+  if pgrep --exact emacs &>/dev/null; then
+    if is_wayland; then
+      if is_gnome && has_run_or_raise; then
+        gdbus call --session --dest org.gnome.Shell \
+          --object-path /org/gnome/Shell/Extensions/RunOrRaise \
+          --method org.gnome.Shell.Extensions.RunOrRaise.Call \
+          ",${EMACS_BIN},,/Lightemacs$/"
+      else
         bg_run "$EMACS_BIN"
-        # "$EMACS_BIN"
+      fi
+    else
+      show_window emacs "emacs.Emacs" "$EMACS_BIN"
     fi
+  else
+    bg_run "$EMACS_BIN"
+    # "$EMACS_BIN"
+  fi
 }
 
 # TODO should this be added back
@@ -107,10 +109,10 @@ start-or-raise-emacs() {
 # }
 
 main() {
-    # cleanup-emacs
-    # Check if Emacs server is running
-    cd
-    start-or-raise-emacs
+  # cleanup-emacs
+  # Check if Emacs server is running
+  cd
+  start-or-raise-emacs
 }
 
 main "$@"
